packages:
  # all packages in subdirs of packages/ and examples/
  - "packages/**"
  - "!packages/**/dist"
  - "examples/**"
  - "docs/**"
  - "!**/.tmp/**"
options:
  prefer-workspace-packages: true
  strict-peer-dependencies: false
